[2022-09-03 14:09:48.115] [remoteagent] [info] Extension host agent started.
[2022-09-03 14:09:48.543] [remoteagent] [info] [127.0.0.1][9a9dff41][ManagementConnection] New connection established.
[2022-09-03 14:09:48.623] [remoteagent] [info] [127.0.0.1][4bef25a3][ExtensionHostConnection] New connection established.
[2022-09-03 14:09:48.627] [remoteagent] [info] [127.0.0.1][4bef25a3][ExtensionHostConnection] <3411> Launched Extension Host Process.
[2022-09-03 14:10:03.472] [remoteagent] [info] [127.0.0.1][9a9dff41][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-03 14:10:03.494] [remoteagent] [info] [127.0.0.1][4bef25a3][ExtensionHostConnection] <3411> Extension Host Process exited with code: 0, signal: null.
[2022-09-03 14:10:03.494] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-09-03 14:10:07.017] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-09-03 14:10:07.017] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-03 14:10:07.423] [remoteagent] [info] [127.0.0.1][bd118d9c][ManagementConnection] New connection established.
[2022-09-03 14:10:07.611] [remoteagent] [info] [127.0.0.1][14844de3][ExtensionHostConnection] New connection established.
[2022-09-03 14:10:07.620] [remoteagent] [info] [127.0.0.1][14844de3][ExtensionHostConnection] <3528> Launched Extension Host Process.
[2022-09-03 14:10:10.037] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 14:15:07.019] [remoteagent] [info] New EH opened, aborting shutdown
[2022-09-03 14:46:38.600] [remoteagent] [info] [127.0.0.1][bd118d9c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-03 14:46:38.614] [remoteagent] [info] [127.0.0.1][14844de3][ExtensionHostConnection] <3528> Extension Host Process exited with code: 0, signal: null.
[2022-09-03 14:46:38.615] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-09-03 14:46:47.171] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-09-03 14:46:47.171] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-03 14:46:47.616] [remoteagent] [info] [127.0.0.1][d5233eff][ManagementConnection] New connection established.
[2022-09-03 14:46:47.758] [remoteagent] [info] [127.0.0.1][4df083f8][ExtensionHostConnection] New connection established.
[2022-09-03 14:46:47.768] [remoteagent] [info] [127.0.0.1][4df083f8][ExtensionHostConnection] <24433> Launched Extension Host Process.
[2022-09-03 14:46:50.044] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 14:46:53.040] [remoteagent] [info] [127.0.0.1][d5233eff][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-03 14:46:53.055] [remoteagent] [info] [127.0.0.1][4df083f8][ExtensionHostConnection] <24433> Extension Host Process exited with code: 0, signal: null.
[2022-09-03 14:46:53.055] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-03 14:46:53.055] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-09-03 14:46:58.623] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-09-03 14:46:58.624] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-03 14:46:59.003] [remoteagent] [info] [127.0.0.1][d92342ac][ManagementConnection] New connection established.
[2022-09-03 14:46:59.183] [remoteagent] [info] [127.0.0.1][f543d5ff][ExtensionHostConnection] New connection established.
[2022-09-03 14:46:59.192] [remoteagent] [info] [127.0.0.1][f543d5ff][ExtensionHostConnection] <24603> Launched Extension Host Process.
[2022-09-03 14:47:01.350] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 14:51:58.624] [remoteagent] [info] New EH opened, aborting shutdown
[2022-09-03 15:53:46.798] [remoteagent] [info] [127.0.0.1][d92342ac][ManagementConnection] The client has reconnected.
[2022-09-03 15:53:46.930] [remoteagent] [info] [127.0.0.1][f543d5ff][ExtensionHostConnection] The client has reconnected.
[2022-09-03 15:53:47.882] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 15:53:47.882] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 15:53:47.882] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-03 15:53:48.864] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
